import Head from 'next/head'
import Image from 'next/image'
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import { Carousel } from 'react-responsive-carousel';
import { BsChevronLeft, BsChevronRight } from 'react-icons/bs'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ecommerce Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='carousel-wrapper'>
        <Carousel renderArrowPrev={(onClickHandler, hasPrev, label) =>
          hasPrev && (
            <button type="button" onClick={onClickHandler} title={label}
              style={{
                position: 'absolute',
                zIndex: 2,
                top: 'calc(50% - 15px)',
                width: 30,
                height: 30, cursor: 'pointer', left: 15
              }}>
              <BsChevronLeft className='text-4xl text-slate-300' />
            </button>
          )
        }
          renderArrowNext={(onClickHandler, hasNext, label) =>
            hasNext && (
              <button type="button" onClick={onClickHandler} title={label}
                style={{
                  position: 'absolute',
                  zIndex: 2,
                  top: 'calc(50% - 15px)',
                  width: 30,
                  height: 30, cursor: 'pointer', right: 15
                }}>
                <BsChevronRight className='text-4xl text-slate-300' />
              </button>
            )
          } showThumbs={false} autoPlay={true} infiniteLoop={true} interval={4000} stopOnHover={false} showStatus={false}>
          <div>
            <img className='h-[50vh] md:h-[80vh]' src="https://www.cloudways.com/blog/wp-content/uploads/Ecommerce-Shopping-Infographics.png" />
          </div>
          <div>
            <img className='h-[50vh] md:h-[80vh]' src="https://blog.3dcart.com/hubfs/iStock-1051616786.jpg" />
          </div>
          <div>
            <img className='h-[50vh] md:h-[80vh]' src="https://s19538.pcdn.co/wp-content/uploads/2021/06/ecommerce.jpg" />
          </div>
          <div>
            <img className='h-[50vh] md:h-[80vh]' src="https://leverageedu.com/blog/wp-content/uploads/2020/05/e-commerce-.jpg" />
          </div>
        </Carousel>

        <section className="text-gray-600 body-font">
          <div className="container px-5 py-12 mx-auto">
            <div className="text-center mb-20">
              <h1 className="sm:text-3xl text-2xl font-medium title-font text-gray-900 mb-4">Our Latest Collections</h1>
              <p className="text-base leading-relaxed xl:w-2/4 lg:w-3/4 mx-auto text-gray-500s">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Praesentium ab aliquam eos eligendi repellendus nesciunt sequi, saepe in?</p>
              <div className="flex mt-6 justify-center">
                <div className="w-16 h-1 rounded-full bg-indigo-500 inline-flex"></div>
              </div>
            </div>
            <div className="container px-1 mx-auto">
              <div className="flex flex-wrap -m-4 justify-center">
                <div className="lg:w-1/5 md:w-1/2 px-1 w-full cursor-pointer shadow-lg m-7">
                  <a className="flex mx-auto justify-center relative rounded overflow-hidden">
                    <img alt="ecommerce" className="m-auto md:m-0 h-[44vh] block" src='iphone.jpg' />
                  </a>
                  <div className="mt-4 flex flex-col justify-center text-center md:text-left">
                    <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">4GB 128GB</h3>
                    <h2 className="text-gray-900 title-font text-lg font-medium">IPHONE 13 PRO MAX</h2>
                    <p className="mt-1">₹ 89,599</p>
                    <div className="mt-1 mb-4">
                      Available in Multiple Colours
                    </div>
                  </div>
                </div>

                <div className="lg:w-1/5 md:w-1/2 px-1 w-full cursor-pointer shadow-lg m-7">
                  <a className="flex mx-auto justify-center relative rounded overflow-hidden">
                    <img alt="ecommerce" className="m-auto md:m-0 h-[44vh] block" src='iphone.jpg' />
                  </a>
                  <div className="mt-4 flex flex-col justify-center text-center md:text-left">
                    <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">4GB 256GB</h3>
                    <h2 className="text-gray-900 title-font text-lg font-medium">IPHONE 13 PRO</h2>
                    <p className="mt-1">₹ 89,099</p>
                    <div className="mt-1 mb-4">
                      Available in Multiple Colours
                    </div>
                  </div>
                </div>

                <div className="lg:w-1/5 md:w-1/2 px-1 w-full cursor-pointer shadow-lg m-7">
                  <a className="flex mx-auto justify-center relative rounded overflow-hidden">
                    <img alt="ecommerce" className="m-auto md:m-0 h-[44vh] block" src='samsung.jpg' />
                  </a>
                  <div className="mt-4 flex flex-col justify-center text-center md:text-left">
                    <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">4GB 128GB</h3>
                    <h2 className="text-gray-900 title-font text-lg font-medium">SAMSUNG S22 ULTRA</h2>
                    <p className="mt-1">₹ 74,999</p>
                    <div className="mt-1 mb-4">
                      Available in Multiple Colours
                    </div>
                  </div>
                </div>

                <div className="lg:w-1/5 md:w-1/2 px-1 w-full cursor-pointer shadow-lg m-7">
                  <a className="flex mx-auto justify-center relative rounded overflow-hidden">
                    <img alt="ecommerce" className="m-auto md:m-0 h-[44vh] block" src='macbook.jpg' />
                  </a>
                  <div className="mt-4 flex flex-col justify-center text-center md:text-left">
                    <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">8GB 512GB HDD 256GB SSD</h3>
                    <h2 className="text-gray-900 title-font text-lg font-medium">MACBOOK AIR</h2>
                    <p className="mt-1">₹ 1,59,999</p>
                    <div className="mt-1 mb-4">
                      Available in Multiple Colours
                    </div>
                  </div>
                </div>

              </div>
            </div>
            <button className="flex mx-auto mt-16 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Checkout all the products</button>
          </div>
        </section>
      </div>

    </div>
  )
}
