import Head from 'next/head'
import Image from 'next/image'
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import { Carousel } from 'react-responsive-carousel';
import { BsChevronLeft, BsChevronRight } from 'react-icons/bs'

export default function Home() {
  return (
    <div className='min-h-screen'>
      <Head>
        <title>Ecommerce Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='carousel-wrapper'>
        <Carousel renderArrowPrev={(onClickHandler, hasPrev, label) =>
          hasPrev && (
            <button type="button" onClick={onClickHandler} title={label}
              style={{
                position: 'absolute',
                zIndex: 2,
                top: 'calc(50% - 15px)',
                width: 30,
                height: 30, cursor: 'pointer', left: 15
              }}>
              <BsChevronLeft className='text-4xl text-slate-300' />
            </button>
          )
        }
          renderArrowNext={(onClickHandler, hasNext, label) =>
            hasNext && (
              <button type="button" onClick={onClickHandler} title={label}
                style={{
                  position: 'absolute',
                  zIndex: 2,
                  top: 'calc(50% - 15px)',
                  width: 30,
                  height: 30, cursor: 'pointer', right: 15
                }}>
                <BsChevronRight className='text-4xl text-slate-300' />
              </button>
            )
          } showThumbs={false} autoPlay={true} infiniteLoop={true} interval={4000} stopOnHover={false} showStatus={false}>
          <div className='h-[80vh]'>
            <img src="https://www.cloudways.com/blog/wp-content/uploads/Ecommerce-Shopping-Infographics.png" />
          </div>
          <div className='h-[80vh]'>
            <img src="https://blog.3dcart.com/hubfs/iStock-1051616786.jpg" />
          </div>
          <div className='h-[80vh]'>
            <img src="https://s19538.pcdn.co/wp-content/uploads/2021/06/ecommerce.jpg" />
          </div>
          <div className='h-[80vh]'>
            <img src="https://leverageedu.com/blog/wp-content/uploads/2020/05/e-commerce-.jpg" />
          </div>
        </Carousel>
      </div>

    </div>
  )
}
